### ISSUE TITLE
the reference article

### ISSUE THREAD

**Issue by echo0202-wmf** [stanford-gps-lab/spoofing-detection#1]
1.Whether the paper that "GNSS Spoof Detection through Spatial Processing" has not been published yet ?
2.how can I download the paper?

**Comment by fabianr-su** [comment]
Hi! The paper can be found here: 
https://doi.org/10.1002/navi.420

**Comment by echo0202-wmf** [comment]
Thanks


















At 2021-07-23 13:17:27, "fabianr-su" ***@***.***> wrote:

Hi! The paper can be found here:
https://doi.org/10.1002/navi.420
